### ISSUE TITLE
How to connect to my ESP32 in dev mode on my windows machine?

### ISSUE THREAD

**Issue by xpix** [pkerspe/ESP-StepperMotor-Server-UI#43]
I have installed the NodeJS and now I want to test your UI, where do I have to specify the ESP32 (REST/IP). In the .env file?

**Comment by pkerspe** [comment]
Hi Frank,

Can you please elaborate on your use case?
Are you planing to run the UI on your PC and connect to the REST API provided by a ESP32 with the server firmware running on it?
Usually you would just upload the UI files or the ESP32s spiffs folder and then connect to the ESP32 in your browser to run the UI directly from the webserver running in the ESP32.
If you intent to locally develop the UI on your PC and connect against an ESP32 just running the rest api that is also possible then you need to enter the IP in the api url configuration parameter in env file: VUE_APP_REST_API_BASE_URL=

Just check the development version of the env file in Git there is an example url.
All you need to do is replace the IP with the IP address of your ESP32 running the stepper motor server firmware.
You can see the IP in the serial console when booting the ESP32

Please follow the installation manual for setting up the Esp32 in the stepper motor server repository

**Comment by xpix** [comment]
Ok, that's what I wanted to know. So I just need to specify the REST URL of my ESP and then I can develop the UI directly on my PC. i would like to use your interface to control my solar tracker via GPS on my TTGO T-Bone. For this the user can then still specify different configurations.
